steps:
- name: 'docker'
  args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_BUILD_TIMESTAMP}', '.']
  #us-docker.pkg.dev/ds-team-384807/gcpdevops
images:
#- 'gcr.io/$PROJECT_ID/gcpdevops'
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_BUILD_TIMESTAMP}'

substitutions:
  _LOCATION: 'us'        # Replace with your desired region
  _REPOSITORY: 'gcpdevops'          # Replace with your Artifact Registry repository name
  _IMAGE: 'gcpdevopssantosh'             # Replace with your image name

logsBucket: 'gs://gcpdevops-s'
serviceAccount: 'projects/ds-team-384807/serviceAccounts/gcp-devops@ds-team-384807.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY