steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BUILD_ID', '.']

- name: 'gcr.io/cloud-builders/docker'
  args:
    ['push','${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BUILD_ID']

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke-deploy.yml
  - --image=${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BUILD_ID
  - --location=${_LOCATION}
  - --cluster=gcp-devops
  - --namespace=gcp-devops-prod

# images:
#   - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$BUILD_ID'

substitutions:
  _LOCATION: 'us'        # Replace with your desired region
  _REPOSITORY: 'gcpdevops'          # Replace with your Artifact Registry repository name
  _IMAGE: 'gcpdevopssantosh'             # Replace with your image name


logsBucket: 'gs://gcpdevops-s'
serviceAccount: 'projects/ds-team-384807/serviceAccounts/gcp-devops@ds-team-384807.iam.gserviceaccount.com'
options:
  logging: GCS_ONLY